extends Node

const MAX_SPEED = 300.0
const MIN_HORIZONTAL_SPEED = 20.0
const MAX_AIR_SPEED = 500.0
const JUMP_VELOCITY = -500.0
const AIR_DRAG = 0.001
const AIR_DRAG_DEGREE = 2  # Air resistance increases quadratically with speed
const GROUND_DRAG = 1
const GROUND_DRAG_DEGREE = 1
const GRAVITY_MODIFIER = 2.0
const STOMP_STOMP_SPEED = 500.0
const CROUCH_STORED_VELOCITY_MAX_BONUS = 200.0
const CROUCH_STORED_VELOCITY_GROWTH = 200.0

const GROUND_ACCEL = GROUND_DRAG * pow(MAX_SPEED, GROUND_DRAG_DEGREE)
const AIR_ACCEL = AIR_DRAG * pow(MAX_AIR_SPEED, AIR_DRAG_DEGREE)

const  JUMP_BUFFER_TIME := 0.075
const  JUMP_TAP_TIME := 0.15
