extends Node

const MAX_SPEED = 300.0
const MIN_HORIZONTAL_SPEED = 20.0
const MAX_AIR_SPEED = 500.0
const JUMP_VELOCITY = -500.0
const AIR_DRAG = 0.001
const AIR_DRAG_DEGREE = 2  # Air resistance increases quadratically with speed

const GROUND_DRAG_CONST = 0.04
const GROUND_DRAG_RUNNING_CONST = 0.08 #RUNNING
const GROUND_DRAG_CHARGE_FORWARD_CONST = 0.08 #CHARGEFORWARD
const GROUND_DRAG_SLIDING_CONST = 0.4 #SLIDING
var GROUND_DRAG = GROUND_DRAG_CONST


const GROUND_DRAG_DEGREE_CONST = 1.5
const GROUND_DRAG_SLIDING_DEGREE_CONST = 1.3 #SLIDING
const GROUND_DRAG_CHARGE_FORWARD_DEGREE_CONST = 1.3 #CHARGEFORWARD
var GROUND_DRAG_DEGREE = GROUND_DRAG_DEGREE_CONST

const GRAVITY_MODIFIER = 2.0
const STOMP_STOMP_SPEED = 500.0
const CROUCH_STORED_VELOCITY_MAX_BONUS = 200.0
const CROUCH_STORED_VELOCITY_GROWTH = 200.0

const CHARGE_WIND_UP_VELOCITY_0 = 300.0

const DIVE_VELOCITY = 300.0

const CHARGE_WIND_HOLD_TIME_1 = 0.5
const CHARGE_WIND_HOLD_TIME_2 = 1
const CHARGE_WIND_HOLD_TIME_3 = 1.5

var GROUND_ACCEL = GROUND_DRAG * pow(MAX_SPEED, GROUND_DRAG_DEGREE)
var AIR_ACCEL = AIR_DRAG * pow(MAX_AIR_SPEED, AIR_DRAG_DEGREE)

const  JUMP_BUFFER_TIME := 0.075
const  JUMP_TAP_TIME := 0.15
